apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
patches:
- path: patch-replica.yaml  
  target:
    kind: Deployment
    name: todoapp
resources: 
- ../../base
commonLabels: 
  env: prod
secretGenerator:
-  name: secret-todoapp-db
   literals:
   - MYSQL_DATABASE=TASKDB
   - MYSQL_PASSWORD=taskpass
   - MYSQL_ROOT_PASSWORD=abrakadabra
   - MYSQL_USER=taskuser