apiVersion: "v1"
kind: "LimitRange"
metadata:
 name: "dev-limits"
spec:
  limits:
  - type: "Container"
    #default value for resources.limit
    default:
      cpu: "100m"
      memory: "100Mi"
    # default values for resources.requests
    defaultRequest:
      cpu: "20m" 
      memory: "20Mi"
