apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources: 
- ../../base
commonLabels: 
  env: testing
namePrefix: testing-
secretGenerator:
  name: secret-todoapp-db
  literals:
  - MYSQL_DATABASE= gorev
  - MYSQL_PASSWORD= gorevParola
  - MYSQL_ROOT_PASSWORD= gorevRoot
  - MYSQL_USER= gorevKullanici
 
